# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='session_key',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
