# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auth_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('session_key', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='auth',
        ),
    ]
