# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160605_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth1',
            old_name='pin',
            new_name='pin_number',
        ),
        migrations.RenameField(
            model_name='auth1',
            old_name='session_key',
            new_name='sessionKey',
        ),
    ]
